/**
 * Conformance of the TypeScript board payload construction against the
 * Python reference (spec/board-payload-vectors.json, generated by
 * scripts/generate_vectors.py — never hand-edit it).
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  boardTimestamp,
  canonicalBoardPayload,
  canonicalBountyAmount,
  postIdFromPayload,
  textHash,
} from "../src/canonical/board.js";

interface BountyVector {
  input: string | null;
  expected?: string | null;
  error?: string;
}

interface BoardPayloadVector {
  name: string;
  wallet: string;
  text: string;
  bounty_amount: string | null;
  timestamp: string;
  nonce: string;
  parent_post_id: string | null;
  expected_bounty_amount: string | null;
  expected_message: string;
  expected_post_id: string;
}

const vectors = JSON.parse(
  readFileSync(
    new URL("../../../spec/board-payload-vectors.json", import.meta.url),
    "utf8",
  ),
) as {
  bounty_normalization: BountyVector[];
  board_payload: BoardPayloadVector[];
};

describe("bounty normalization", () => {
  for (const vector of vectors.bounty_normalization) {
    it(`canonicalizes ${JSON.stringify(vector.input)}`, () => {
      if (vector.error !== undefined) {
        expect(() => canonicalBountyAmount(vector.input)).toThrow();
      } else {
        expect(canonicalBountyAmount(vector.input)).toBe(vector.expected);
      }
    });
  }
});

describe("board payload vectors", () => {
  for (const vector of vectors.board_payload) {
    it(vector.name, () => {
      const message = canonicalBoardPayload({
        wallet: vector.wallet,
        text: vector.text,
        bountyAmount: canonicalBountyAmount(vector.bounty_amount),
        timestamp: vector.timestamp,
        nonce: vector.nonce,
        parentPostId: vector.parent_post_id,
      });
      expect(message).toBe(vector.expected_message);
      expect(postIdFromPayload(message)).toBe(vector.expected_post_id);
    });
  }
});

describe("board payload shape", () => {
  it("hashes text with python strip semantics", () => {
    expect(textHash("  x  ")).toBe(textHash("x"));
    expect(textHash("\x1cx\x1f")).toBe(textHash("x"));
  });

  it("emits second-precision UTC timestamps", () => {
    const stamp = boardTimestamp(new Date("2026-08-19T12:00:00.123Z"));
    expect(stamp).toBe("2026-08-19T12:00:00Z");
  });

  it("comment payloads carry parent_post_id, post payloads do not", () => {
    const base = {
      wallet: "0x" + "ab".repeat(20),
      text: "x",
      bountyAmount: null,
      timestamp: "2026-08-19T12:00:00Z",
      nonce: "00".repeat(8),
    };
    const post = JSON.parse(canonicalBoardPayload(base));
    expect(post.type).toBe("crowdcode.post.v1");
    expect(post.parent_post_id).toBeUndefined();
    const comment = JSON.parse(
      canonicalBoardPayload({ ...base, parentPostId: "post_" + "0".repeat(20) }),
    );
    expect(comment.type).toBe("crowdcode.comment.v1");
    expect(comment.parent_post_id).toBe("post_" + "0".repeat(20));
  });
});
